# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TradingCli < Formula
  desc "Technical analysis and trading tools CLI"
  homepage "https://github.com/alorse/trading-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alorse/trading-cli/releases/download/v0.1.3/trading-cli_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "d73266a25fd6044abe41311f4ef85b00dfa19a65fc39d34138fd697f979ae278"

      define_method(:install) do
        bin.install "trading-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alorse/trading-cli/releases/download/v0.1.3/trading-cli_0.1.3_Darwin_arm64.tar.gz"
      sha256 "c1aaf79f1417f89578f39e17d8de2841e4b53fef1972073dae259db4f5a14825"

      define_method(:install) do
        bin.install "trading-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alorse/trading-cli/releases/download/v0.1.3/trading-cli_0.1.3_Linux_x86_64.tar.gz"
      sha256 "29286eddadfccc13766a0b7c8d56172cead925f648b31b1491f767b70ff9766c"
      define_method(:install) do
        bin.install "trading-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alorse/trading-cli/releases/download/v0.1.3/trading-cli_0.1.3_Linux_arm64.tar.gz"
      sha256 "24d00965be03172896b776d0678b317402d5525311777395ce02a098be279c8f"
      define_method(:install) do
        bin.install "trading-cli"
      end
    end
  end

  test do
    system "#{bin}/trading-cli", "version"
  end
end
